FROM golang:1.25-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=1 GOOS=linux go build -o api ./cmd/api/main.go

FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/api .

ENV DB_PATH=/app/data/session.db
ENV PORT=:8081
VOLUME /app/data
EXPOSE 8081

ENTRYPOINT ["./api"]
